spring:
  # DB 연결
  datasource:
    url: jdbc:mysql://146.56.182.42/gogetters
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: PiI4I65otC04Ut
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  # 콘솔 확인 을 위한 always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  output:
    ansi:
      enabled: always
