spring:
  redis:
    host: localhost
    port: 6379
  #jwt
  jwt:
    secret: _3SjJfvYUyRtNkMBQUVJQrjRaH9ioihgB0H9LueZkHQEpTtD8Kmgdyo2UjVpTDbyhwC6wQpzkeXuH4BdCznH3kd34pMMH1Yl3R13imu_vtG_XQZhmTij6lnDdBg0UBPBdpQBgRMQOM


logging:
  level:
    org.hibernate.SQL: debug
    com.zaxxer.hikari.pool.HikariPool: info
  config: classpath:logback-${spring.profiles.active}.xml
---
# 운영 서버
spring:
  profiles:
    active: prod


---
# 개발 서버
spring:
  profiles:
    active: dev

---
# 로컬 서버
spring:
  profiles:
    active: local
