spring:
  datasource:
    # 설치된 H2 DB와 연결 URL
    url: jdbc:mariadb://database-1.choj938t9lhu.ap-northeast-2.rds.amazonaws.com/GoGetter
    # 접속을 위한 드라이버
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rlagudtn4510

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  output:
    ansi:
      enabled: always


logging:
  level:
    org.hibernate.type: info