spring:
  redis:
    host: localhost
    port: 6379
  #jwt
  jwt:
    secret: kimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeun
---
# 운영 서버
spring:
  profiles:
    active: prod

---
# 개발 서버
spring:
  profiles:
    active: dev

---
# 로컬 서버
spring:
  profiles:
    active: local
