spring:
  # DB 연결
  datasource:
    url: jdbc:h2:tcp://localhost/~/GoGetter
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    # JPA가 수행하는 SQL을 볼 수 있다.
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  # 콘솔 확인 을 위한 always
  output:
    ansi:
      enabled: always

# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace